# production properties
spring.application.name=rookwork-backend-sb

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:604800000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:2592000000}

spring.jackson.serialization.write-dates-as-timestamps=false

