spring.cloud.aws.secretsmanager.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/rookwork-db
spring.datasource.username=postgres
spring.datasource.password=datvip123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1

jwt.secret=ZF3942XJYFfn28lZBkosu5qBUktNB79AVsCmhQ4a0Anv6uDANbVVw5UkXFEt+KSdhnSRVS6vVWhdnAAdEDHy0Q==
jwt.expiration=604800000
jwt.refresh-expiration=2592000000

google.client-id=880086216099-lr6aqg0401fatdmgvm6b86npvr0m2jo3.apps.googleusercontent.com