ALTER TABLE users
ADD COLUMN job_title VARCHAR(255),
ADD COLUMN theme VARCHAR(50) DEFAULT 'system',
ADD COLUMN language VARCHAR(50) DEFAULT 'en',
ADD COLUMN date_format VARCHAR(50) DEFAULT 'DD/MM/YYYY',
ADD COLUMN notify_issue_assigned BOOLEAN DEFAULT TRUE,
ADD COLUMN notify_mentioned BOOLEAN DEFAULT TRUE,
ADD COLUMN notify_project_updates BOOLEAN DEFAULT FALSE,
ADD COLUMN notify_daily_digest BOOLEAN DEFAULT FALSE;
