ALTER TABLE users 
ADD COLUMN IF NOT EXISTS email_public BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS job_title_public BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS organization_public BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS location_public BOOLEAN DEFAULT true;
